excluded:
  - .build
disabled_rules:
  - colon
  - cyclomatic_complexity
  - todo
  - force_cast

identifier_name:
    min_length: 1

line_length:
    warning: 200
    error: 250
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true