name: WalletSdk
options:
  bundleIdPrefix: com.spruceid.wallet.sdk
packages:
  SpruceIDWalletSdkRs:
    url: https://github.com/spruceid/wallet-sdk-rs
    # from: 0.0.4
    path: "../wallet-sdk-rs"
  SwiftAlgorithms:
    url: https://github.com/apple/swift-algorithms
    from: 1.2.0
  SwiftLint:
    url: https://github.com/realm/SwiftLint
    from: 0.54.0
settings:
  ENABLE_USER_SCRIPT_SANDBOXING: YES
  GENERATE_INFOPLIST_FILE: YES
  DEVELOPMENT_TEAM: FZVYR3KYL4
targets:
  WalletSdk:
    type: library.dynamic
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - Sources
    dependencies:
      - package: SpruceIDWalletSdkRs
      - package: SwiftAlgorithms
        product: Algorithms
    scheme:
      testTargets:
        - WalletSdkTests
    info:
      path: Info.plist
      properties:
        NSBluetoothAlwaysUsageDescription: "Secure transmission of mobile DL data"
    buildToolPlugins:
      - plugin: SwiftLintPlugin
        package: SwiftLint
  WalletSdkTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - Tests
    dependencies:
      - target: WalletSdk
